version: "3.7"

services:
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${CONFIG_DIR}/jellyfin:/config"
      - "${MEDIA_DIR}:/media"
    ports:
      - "8096:8096/tcp"
      - "7359:7359/udp"

  sonarr:
    image: ghcr.io/linuxserver/sonarr
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${CONFIG_DIR}/sonarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    ports:
      - "8989:8989/tcp"

  radarr:
    image: ghcr.io/linuxserver/radarr
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${CONFIG_DIR}/radarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    ports:
      - "7878:7878/tcp"

  ombi:
    image: ghcr.io/linuxserver/ombi
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${CONFIG_DIR}/ombi:/config"
    ports:
      - "3579:3579/tcp"
  
  deluge:
    image: ghcr.io/linuxserver/deluge
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${CONFIG_DIR}/deluge:/config"
      - "${DOWNLOADS_DIR}:/downloads"
    ports:
      - "8112:8112/tcp"
      - "8118:8118/tcp"
      - "58846:58846/tcp"
      - "58946:58946/tcp"

  jackett:
    image: ghcr.io/linuxserver/jackett
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - "${CONFIG_DIR}/jackett:/config"
      - "${DOWNLOADS_DIR}:/downloads"
    ports:
      - "9117:9117/tcp"
