version: '3.7'

networks:
    backend:

volumes:
    duplicati:
    nextcloud:
    ghost:
    ombi:
    mariadb:

services:

    # https://hub.docker.com/r/linuxserver/ombi
    ombi:
        image: linuxserver/ombi
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        volumes:
            - ombi:/config
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.ombi.rule: Host(`${OMBI_HOST}`)
            traefik.http.routers.ombi.tls.certresolver: prod
            traefik.http.routers.ombi.middlewares: hsts-header
        networks:
            - frontend
        links:
            - sonarr
            - radarr
            - plex

    # https://hub.docker.com/_/nextcloud/
    nextcloud:
        image: nextcloud
        volumes:
            - nextcloud:/var/www/html
        environment:
            MYSQL_HOST: mariadb
            MYSQL_DATABASE: nextcloud
            MYSQL_USER: nextcloud
            MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
            TZ: ${TZ}
            NEXTCLOUD_TRUSTED_DOMAINS: ${NEXTCLOUD_HOST}
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.nextcloud.rule: Host(`${NEXTCLOUD_HOST}`)
            traefik.http.routers.nextcloud.tls.certresolver: prod
            traefik.http.routers.nextcloud.middlewares: hsts-header, cardcaldav
            traefik.http.middlewares.cardcaldav.replacepathregex.regex: ^/.well-known/(card|cal)dav
            traefik.http.middlewares.cardcaldav.replacepathregex.replacement: /remote.php/dav/
        networks:
            - frontend
            - backend
        links:
            - mariadb

    # https://hub.docker.com/_/ghost/
    ghost:
        image: ghost
        environment:
            TZ: ${TZ}
            url: https://${GHOST_HOST}
            database__client: mysql
            database__connection__host: mariadb
            database__connection__database: ghost
            database__connection__user: ghost
            database__connection__password: ${GHOST_DB_PASSWORD}
        volumes:
            - 'ghost:/var/lib/ghost/content:rw'
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.ghost.rule: Host(`${GHOST_HOST}`)
            traefik.http.routers.ghost.tls.certresolver: prod
            traefik.http.routers.ghost.middlewares: hsts-header, basicauth
            traefik.http.routers.ghost-admin.rule: Host(`${GHOST_HOST}`) && PathPrefix(`/ghost`)
            traefik.http.routers.ghost-admin.middlewares: hsts-header, basicauth
        networks:
            - frontend
            - backend
        links:
            - mariadb

    # https://hub.docker.com/r/linuxserver/duplicati
    duplicati:
        image: linuxserver/duplicati
        environment:
            PUID: 0
            PGID: 0
            TZ: ${TZ}
        volumes:
            - duplicati:/config:rw
            - plex:/sources/plex:ro
            - nzbget:/sources/nzbget:ro
            - sonarr:/sources/sonarr:ro
            - radarr:/sources/radarr:ro
            - hydra:/sources/hydra:ro
            - nextcloud:/sources/nextcloud:ro
            - mariadb:/sources/mariadb:ro
            - ghost:/sources/ghost:ro
            - ombi:/sources/ombi:ro
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.duplicati.rule: Host(`${DUPLICATI_HOST}`)
            traefik.http.routers.duplicati.tls.certresolver: prod
            traefik.http.routers.duplicati.middlewares: hsts-header, basicauth
        networks:
            - frontend

    # https://hub.docker.com/r/netdata/netdata
    netdata:
        image: netdata/netdata
        hostname: ${NETDATA_HOST}
        environment:
            PUID: ${PUID}
            PGID: ${PGID}
            TZ: ${TZ}
        cap_add:
            - SYS_PTRACE
        security_opt:
            - apparmor:unconfined
        volumes:
            - /etc/passwd:/host/etc/passwd:ro
            - /etc/group:/host/etc/group:ro
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            traefik.enable: true
            traefik.docker.network: mediaserver_frontend
            traefik.http.routers.netdata.tls.certresolver: prod
            traefik.http.routers.netdata.rule: Host(`${NETDATA_HOST}`)
            traefik.http.routers.netdata.middlewares: hsts-header, basicauth
        networks:
            - frontend

    # https://hub.docker.com/_/mariadb/
    mariadb:
        image: mariadb
        volumes:
            - mariadb:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            TZ: ${TZ}
        networks:
            - backend
