version: "3.7"

networks:
  default:

volumes:
  plex:
  nzbget:
  sonarr:
  radarr:
  nzbhydra:
  ombi:
  duplicati:
  traefik:

services:
  # https://hub.docker.com/r/linuxserver/plex/
  plex:
    image: linuxserver/plex
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
      PLEX_CLAIM: "${PLEX_CLAIM}"
    networks:
      - default
    ports:
      - "32400:32400/tcp"
    volumes:
      - "plex:/config"
      - "${MEDIA_DIR}:/media"
      - "/tmp:/tmp"

  # https://hub.docker.com/r/linuxserver/nzbget/
  nzbget:
    image: linuxserver/nzbget
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    ports:
      - "6789:6789/tcp"
    volumes:
      - "nzbget:/config"
      - "${DOWNLOADS_DIR}:/downloads"

  # https://hub.docker.com/r/linuxserver/sonarr/
  sonarr:
    image: linuxserver/sonarr
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    ports:
      - "8989:8989/tcp"
    volumes:
      - "sonarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    links:
      - nzbhydra
      - nzbget

  # https://hub.docker.com/r/linuxserver/radarr/
  radarr:
    image: linuxserver/radarr
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    ports:
      - "7878:7878/tcp"
    volumes:
      - "radarr:/config"
      - "${DOWNLOADS_DIR}:/downloads"
      - "${MEDIA_DIR}:/media"
    links:
      - nzbhydra
      - nzbget

  # https://hub.docker.com/r/linuxserver/nzbhydra2
  nzbhydra:
    image: linuxserver/nzbhydra2
    restart: unless-stopped
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
      TZ: "${TZ}"
    networks:
      - default
    ports:
      - "5076:5076/tcp"
    volumes:
      - "nzbhydra:/config"
      - "${DOWNLOADS_DIR}:/downloads"

  # https://hub.docker.com/r/linuxserver/ombi
  ombi:
    image: linuxserver/ombi
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
    volumes:
      - ombi:/config
    ports:
      - "3579:3579/tcp"
    networks:
      - default
    links:
      - sonarr
      - radarr
      - plex

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati
    restart: unless-stopped
    environment:
      PUID: 0
      PGID: 0
      TZ: ${TZ}
    ports:
      - "8200:8200/tcp"
    volumes:
      - duplicati:/config:rw
      - plex:/sources/plex:rw
      - nzbget:/sources/nzbget:rw
      - sonarr:/sources/sonarr:rw
      - radarr:/sources/radarr:rw
      - nzbhydra:/sources/nzbhydra:rw
      - ombi:/sources/ombi:rw
      - traefik:/sources/traefik:rw
    networks:
      - default

  # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata
    restart: unless-stopped
    hostname: ${NETDATA_HOST}
    environment:
      PGID: ${DOCKER_PGID}
      TZ: ${TZ}
    ports:
      - "19999:19999/tcp"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor:unconfined
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - default
